drop policy "User access to dietary_profiles" on "public"."dietary_profiles";

revoke delete on table "public"."dietary_profiles" from "anon";

revoke insert on table "public"."dietary_profiles" from "anon";

revoke references on table "public"."dietary_profiles" from "anon";

revoke select on table "public"."dietary_profiles" from "anon";

revoke trigger on table "public"."dietary_profiles" from "anon";

revoke truncate on table "public"."dietary_profiles" from "anon";

revoke update on table "public"."dietary_profiles" from "anon";

revoke delete on table "public"."dietary_profiles" from "authenticated";

revoke insert on table "public"."dietary_profiles" from "authenticated";

revoke references on table "public"."dietary_profiles" from "authenticated";

revoke select on table "public"."dietary_profiles" from "authenticated";

revoke trigger on table "public"."dietary_profiles" from "authenticated";

revoke truncate on table "public"."dietary_profiles" from "authenticated";

revoke update on table "public"."dietary_profiles" from "authenticated";

revoke delete on table "public"."dietary_profiles" from "service_role";

revoke insert on table "public"."dietary_profiles" from "service_role";

revoke references on table "public"."dietary_profiles" from "service_role";

revoke select on table "public"."dietary_profiles" from "service_role";

revoke trigger on table "public"."dietary_profiles" from "service_role";

revoke truncate on table "public"."dietary_profiles" from "service_role";

revoke update on table "public"."dietary_profiles" from "service_role";

revoke delete on table "public"."meals" from "anon";

revoke insert on table "public"."meals" from "anon";

revoke references on table "public"."meals" from "anon";

revoke select on table "public"."meals" from "anon";

revoke trigger on table "public"."meals" from "anon";

revoke truncate on table "public"."meals" from "anon";

revoke update on table "public"."meals" from "anon";

revoke delete on table "public"."meals" from "authenticated";

revoke insert on table "public"."meals" from "authenticated";

revoke references on table "public"."meals" from "authenticated";

revoke select on table "public"."meals" from "authenticated";

revoke trigger on table "public"."meals" from "authenticated";

revoke truncate on table "public"."meals" from "authenticated";

revoke update on table "public"."meals" from "authenticated";

revoke delete on table "public"."meals" from "service_role";

revoke insert on table "public"."meals" from "service_role";

revoke references on table "public"."meals" from "service_role";

revoke select on table "public"."meals" from "service_role";

revoke trigger on table "public"."meals" from "service_role";

revoke truncate on table "public"."meals" from "service_role";

revoke update on table "public"."meals" from "service_role";

alter table "public"."dietary_profiles" drop constraint "dietary_profiles_user_id_fkey";

alter table "public"."dietary_profiles" drop constraint "dietary_profiles_pkey";

drop index if exists "public"."dietary_profiles_pkey";

drop table "public"."dietary_profiles";

drop table "public"."meals";


  create table "public"."dining_halls" (
    "dc_id" bigint generated by default as identity not null,
    "updated_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "payment_accepted" jsonb,
    "dc_name" text,
    "hour_open" time without time zone,
    "hour_closed" time without time zone,
    "current_meals" json
      );


alter table "public"."dining_halls" enable row level security;


  create table "public"."favorite_meals" (
    "saved_meal_id" bigint generated always as identity not null,
    "user_id" uuid not null,
    "meal_id" uuid not null,
    "saved_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."favorite_meals" enable row level security;


  create table "public"."ingredient_reference" (
    "ingredient_id" bigint generated always as identity not null,
    "ingredient_name" text not null
      );


alter table "public"."ingredient_reference" enable row level security;


  create table "public"."meal_ingredients" (
    "meal_id" uuid not null,
    "ingredient_name" text not null
      );


alter table "public"."meal_ingredients" enable row level security;


  create table "public"."meal_log" (
    "log_id" bigint generated always as identity not null,
    "user_id" uuid not null,
    "meal_id" uuid not null,
    "eaten_date" date default CURRENT_DATE,
    "created_at" timestamp with time zone default timezone('utc'::text, now())
      );


alter table "public"."meal_log" enable row level security;


  create table "public"."meal_restrictions" (
    "meal_id" uuid not null,
    "restriction_name" text not null
      );


alter table "public"."meal_restrictions" enable row level security;


  create table "public"."meals_list" (
    "meal_id" uuid not null default gen_random_uuid(),
    "meal_name" text not null,
    "calories" integer,
    "protein" integer,
    "fiber" integer,
    "recipe_link" text,
    "dining_hall_id" bigint,
    "created_at" timestamp with time zone default timezone('utc'::text, now()),
    "instructions" text,
    "ingredients" text
      );


alter table "public"."meals_list" enable row level security;


  create table "public"."restriction_reference" (
    "restriction_id" bigint generated always as identity not null,
    "restriction_name" text not null
      );


alter table "public"."restriction_reference" enable row level security;


  create table "public"."user_ingredient_preferences" (
    "user_id" uuid not null,
    "ingredient_name" text not null,
    "want" boolean default true
      );


alter table "public"."user_ingredient_preferences" enable row level security;


  create table "public"."user_profile" (
    "user_id" uuid not null,
    "max_calories" integer,
    "min_protein" integer,
    "allergies" text[],
    "preferences" text,
    "full_name" text
      );


alter table "public"."user_profile" enable row level security;


  create table "public"."user_restriction_preferences" (
    "user_id" uuid not null,
    "restriction_name" text not null,
    "want" boolean default true
      );


alter table "public"."user_restriction_preferences" enable row level security;

CREATE UNIQUE INDEX dining_halls_pkey ON public.dining_halls USING btree (dc_id);

CREATE UNIQUE INDEX favorite_meals_pkey ON public.favorite_meals USING btree (saved_meal_id);

CREATE UNIQUE INDEX favorite_meals_user_id_meal_id_key ON public.favorite_meals USING btree (user_id, meal_id);

CREATE UNIQUE INDEX ingredient_reference_ingredient_name_key ON public.ingredient_reference USING btree (ingredient_name);

CREATE UNIQUE INDEX ingredient_reference_pkey ON public.ingredient_reference USING btree (ingredient_id);

CREATE UNIQUE INDEX meal_ingredients_pkey ON public.meal_ingredients USING btree (meal_id, ingredient_name);

CREATE UNIQUE INDEX meal_log_pkey ON public.meal_log USING btree (log_id);

CREATE UNIQUE INDEX meal_restrictions_pkey ON public.meal_restrictions USING btree (meal_id, restriction_name);

CREATE UNIQUE INDEX meals_list_pkey ON public.meals_list USING btree (meal_id);

CREATE UNIQUE INDEX restriction_reference_pkey ON public.restriction_reference USING btree (restriction_id);

CREATE UNIQUE INDEX restriction_reference_restriction_name_key ON public.restriction_reference USING btree (restriction_name);

CREATE UNIQUE INDEX user_ingredient_preferences_pkey ON public.user_ingredient_preferences USING btree (user_id, ingredient_name);

CREATE UNIQUE INDEX user_restriction_preferences_pkey ON public.user_restriction_preferences USING btree (user_id, restriction_name);

CREATE UNIQUE INDEX dietary_profiles_pkey ON public.user_profile USING btree (user_id);

alter table "public"."dining_halls" add constraint "dining_halls_pkey" PRIMARY KEY using index "dining_halls_pkey";

alter table "public"."favorite_meals" add constraint "favorite_meals_pkey" PRIMARY KEY using index "favorite_meals_pkey";

alter table "public"."ingredient_reference" add constraint "ingredient_reference_pkey" PRIMARY KEY using index "ingredient_reference_pkey";

alter table "public"."meal_ingredients" add constraint "meal_ingredients_pkey" PRIMARY KEY using index "meal_ingredients_pkey";

alter table "public"."meal_log" add constraint "meal_log_pkey" PRIMARY KEY using index "meal_log_pkey";

alter table "public"."meal_restrictions" add constraint "meal_restrictions_pkey" PRIMARY KEY using index "meal_restrictions_pkey";

alter table "public"."meals_list" add constraint "meals_list_pkey" PRIMARY KEY using index "meals_list_pkey";

alter table "public"."restriction_reference" add constraint "restriction_reference_pkey" PRIMARY KEY using index "restriction_reference_pkey";

alter table "public"."user_ingredient_preferences" add constraint "user_ingredient_preferences_pkey" PRIMARY KEY using index "user_ingredient_preferences_pkey";

alter table "public"."user_profile" add constraint "dietary_profiles_pkey" PRIMARY KEY using index "dietary_profiles_pkey";

alter table "public"."user_restriction_preferences" add constraint "user_restriction_preferences_pkey" PRIMARY KEY using index "user_restriction_preferences_pkey";

alter table "public"."favorite_meals" add constraint "favorite_meals_meal_id_fkey" FOREIGN KEY (meal_id) REFERENCES public.meals_list(meal_id) ON DELETE CASCADE not valid;

alter table "public"."favorite_meals" validate constraint "favorite_meals_meal_id_fkey";

alter table "public"."favorite_meals" add constraint "favorite_meals_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profile(user_id) ON DELETE CASCADE not valid;

alter table "public"."favorite_meals" validate constraint "favorite_meals_user_id_fkey";

alter table "public"."favorite_meals" add constraint "favorite_meals_user_id_meal_id_key" UNIQUE using index "favorite_meals_user_id_meal_id_key";

alter table "public"."ingredient_reference" add constraint "ingredient_reference_ingredient_name_key" UNIQUE using index "ingredient_reference_ingredient_name_key";

alter table "public"."meal_ingredients" add constraint "meal_ingredients_meal_id_fkey" FOREIGN KEY (meal_id) REFERENCES public.meals_list(meal_id) ON DELETE CASCADE not valid;

alter table "public"."meal_ingredients" validate constraint "meal_ingredients_meal_id_fkey";

alter table "public"."meal_log" add constraint "meal_log_meal_id_fkey" FOREIGN KEY (meal_id) REFERENCES public.meals_list(meal_id) not valid;

alter table "public"."meal_log" validate constraint "meal_log_meal_id_fkey";

alter table "public"."meal_log" add constraint "meal_log_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profile(user_id) ON DELETE CASCADE not valid;

alter table "public"."meal_log" validate constraint "meal_log_user_id_fkey";

alter table "public"."meal_restrictions" add constraint "meal_restrictions_meal_id_fkey" FOREIGN KEY (meal_id) REFERENCES public.meals_list(meal_id) ON DELETE CASCADE not valid;

alter table "public"."meal_restrictions" validate constraint "meal_restrictions_meal_id_fkey";

alter table "public"."meals_list" add constraint "meals_list_dining_hall_id_fkey" FOREIGN KEY (dining_hall_id) REFERENCES public.dining_halls(dc_id) not valid;

alter table "public"."meals_list" validate constraint "meals_list_dining_hall_id_fkey";

alter table "public"."restriction_reference" add constraint "restriction_reference_restriction_name_key" UNIQUE using index "restriction_reference_restriction_name_key";

alter table "public"."user_ingredient_preferences" add constraint "user_ingredient_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profile(user_id) ON DELETE CASCADE not valid;

alter table "public"."user_ingredient_preferences" validate constraint "user_ingredient_preferences_user_id_fkey";

alter table "public"."user_profile" add constraint "dietary_profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."user_profile" validate constraint "dietary_profiles_user_id_fkey";

alter table "public"."user_profile" add constraint "user_profile_full_name_check" CHECK ((length(full_name) <= 30)) not valid;

alter table "public"."user_profile" validate constraint "user_profile_full_name_check";

alter table "public"."user_restriction_preferences" add constraint "user_restriction_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.user_profile(user_id) ON DELETE CASCADE not valid;

alter table "public"."user_restriction_preferences" validate constraint "user_restriction_preferences_user_id_fkey";

grant delete on table "public"."dining_halls" to "anon";

grant insert on table "public"."dining_halls" to "anon";

grant references on table "public"."dining_halls" to "anon";

grant select on table "public"."dining_halls" to "anon";

grant trigger on table "public"."dining_halls" to "anon";

grant truncate on table "public"."dining_halls" to "anon";

grant update on table "public"."dining_halls" to "anon";

grant delete on table "public"."dining_halls" to "authenticated";

grant insert on table "public"."dining_halls" to "authenticated";

grant references on table "public"."dining_halls" to "authenticated";

grant select on table "public"."dining_halls" to "authenticated";

grant trigger on table "public"."dining_halls" to "authenticated";

grant truncate on table "public"."dining_halls" to "authenticated";

grant update on table "public"."dining_halls" to "authenticated";

grant delete on table "public"."dining_halls" to "service_role";

grant insert on table "public"."dining_halls" to "service_role";

grant references on table "public"."dining_halls" to "service_role";

grant select on table "public"."dining_halls" to "service_role";

grant trigger on table "public"."dining_halls" to "service_role";

grant truncate on table "public"."dining_halls" to "service_role";

grant update on table "public"."dining_halls" to "service_role";

grant delete on table "public"."favorite_meals" to "anon";

grant insert on table "public"."favorite_meals" to "anon";

grant references on table "public"."favorite_meals" to "anon";

grant select on table "public"."favorite_meals" to "anon";

grant trigger on table "public"."favorite_meals" to "anon";

grant truncate on table "public"."favorite_meals" to "anon";

grant update on table "public"."favorite_meals" to "anon";

grant delete on table "public"."favorite_meals" to "authenticated";

grant insert on table "public"."favorite_meals" to "authenticated";

grant references on table "public"."favorite_meals" to "authenticated";

grant select on table "public"."favorite_meals" to "authenticated";

grant trigger on table "public"."favorite_meals" to "authenticated";

grant truncate on table "public"."favorite_meals" to "authenticated";

grant update on table "public"."favorite_meals" to "authenticated";

grant delete on table "public"."favorite_meals" to "service_role";

grant insert on table "public"."favorite_meals" to "service_role";

grant references on table "public"."favorite_meals" to "service_role";

grant select on table "public"."favorite_meals" to "service_role";

grant trigger on table "public"."favorite_meals" to "service_role";

grant truncate on table "public"."favorite_meals" to "service_role";

grant update on table "public"."favorite_meals" to "service_role";

grant delete on table "public"."ingredient_reference" to "anon";

grant insert on table "public"."ingredient_reference" to "anon";

grant references on table "public"."ingredient_reference" to "anon";

grant select on table "public"."ingredient_reference" to "anon";

grant trigger on table "public"."ingredient_reference" to "anon";

grant truncate on table "public"."ingredient_reference" to "anon";

grant update on table "public"."ingredient_reference" to "anon";

grant delete on table "public"."ingredient_reference" to "authenticated";

grant insert on table "public"."ingredient_reference" to "authenticated";

grant references on table "public"."ingredient_reference" to "authenticated";

grant select on table "public"."ingredient_reference" to "authenticated";

grant trigger on table "public"."ingredient_reference" to "authenticated";

grant truncate on table "public"."ingredient_reference" to "authenticated";

grant update on table "public"."ingredient_reference" to "authenticated";

grant delete on table "public"."ingredient_reference" to "service_role";

grant insert on table "public"."ingredient_reference" to "service_role";

grant references on table "public"."ingredient_reference" to "service_role";

grant select on table "public"."ingredient_reference" to "service_role";

grant trigger on table "public"."ingredient_reference" to "service_role";

grant truncate on table "public"."ingredient_reference" to "service_role";

grant update on table "public"."ingredient_reference" to "service_role";

grant delete on table "public"."meal_ingredients" to "anon";

grant insert on table "public"."meal_ingredients" to "anon";

grant references on table "public"."meal_ingredients" to "anon";

grant select on table "public"."meal_ingredients" to "anon";

grant trigger on table "public"."meal_ingredients" to "anon";

grant truncate on table "public"."meal_ingredients" to "anon";

grant update on table "public"."meal_ingredients" to "anon";

grant delete on table "public"."meal_ingredients" to "authenticated";

grant insert on table "public"."meal_ingredients" to "authenticated";

grant references on table "public"."meal_ingredients" to "authenticated";

grant select on table "public"."meal_ingredients" to "authenticated";

grant trigger on table "public"."meal_ingredients" to "authenticated";

grant truncate on table "public"."meal_ingredients" to "authenticated";

grant update on table "public"."meal_ingredients" to "authenticated";

grant delete on table "public"."meal_ingredients" to "service_role";

grant insert on table "public"."meal_ingredients" to "service_role";

grant references on table "public"."meal_ingredients" to "service_role";

grant select on table "public"."meal_ingredients" to "service_role";

grant trigger on table "public"."meal_ingredients" to "service_role";

grant truncate on table "public"."meal_ingredients" to "service_role";

grant update on table "public"."meal_ingredients" to "service_role";

grant delete on table "public"."meal_log" to "anon";

grant insert on table "public"."meal_log" to "anon";

grant references on table "public"."meal_log" to "anon";

grant select on table "public"."meal_log" to "anon";

grant trigger on table "public"."meal_log" to "anon";

grant truncate on table "public"."meal_log" to "anon";

grant update on table "public"."meal_log" to "anon";

grant delete on table "public"."meal_log" to "authenticated";

grant insert on table "public"."meal_log" to "authenticated";

grant references on table "public"."meal_log" to "authenticated";

grant select on table "public"."meal_log" to "authenticated";

grant trigger on table "public"."meal_log" to "authenticated";

grant truncate on table "public"."meal_log" to "authenticated";

grant update on table "public"."meal_log" to "authenticated";

grant delete on table "public"."meal_log" to "service_role";

grant insert on table "public"."meal_log" to "service_role";

grant references on table "public"."meal_log" to "service_role";

grant select on table "public"."meal_log" to "service_role";

grant trigger on table "public"."meal_log" to "service_role";

grant truncate on table "public"."meal_log" to "service_role";

grant update on table "public"."meal_log" to "service_role";

grant delete on table "public"."meal_restrictions" to "anon";

grant insert on table "public"."meal_restrictions" to "anon";

grant references on table "public"."meal_restrictions" to "anon";

grant select on table "public"."meal_restrictions" to "anon";

grant trigger on table "public"."meal_restrictions" to "anon";

grant truncate on table "public"."meal_restrictions" to "anon";

grant update on table "public"."meal_restrictions" to "anon";

grant delete on table "public"."meal_restrictions" to "authenticated";

grant insert on table "public"."meal_restrictions" to "authenticated";

grant references on table "public"."meal_restrictions" to "authenticated";

grant select on table "public"."meal_restrictions" to "authenticated";

grant trigger on table "public"."meal_restrictions" to "authenticated";

grant truncate on table "public"."meal_restrictions" to "authenticated";

grant update on table "public"."meal_restrictions" to "authenticated";

grant delete on table "public"."meal_restrictions" to "service_role";

grant insert on table "public"."meal_restrictions" to "service_role";

grant references on table "public"."meal_restrictions" to "service_role";

grant select on table "public"."meal_restrictions" to "service_role";

grant trigger on table "public"."meal_restrictions" to "service_role";

grant truncate on table "public"."meal_restrictions" to "service_role";

grant update on table "public"."meal_restrictions" to "service_role";

grant delete on table "public"."meals_list" to "anon";

grant insert on table "public"."meals_list" to "anon";

grant references on table "public"."meals_list" to "anon";

grant select on table "public"."meals_list" to "anon";

grant trigger on table "public"."meals_list" to "anon";

grant truncate on table "public"."meals_list" to "anon";

grant update on table "public"."meals_list" to "anon";

grant delete on table "public"."meals_list" to "authenticated";

grant insert on table "public"."meals_list" to "authenticated";

grant references on table "public"."meals_list" to "authenticated";

grant select on table "public"."meals_list" to "authenticated";

grant trigger on table "public"."meals_list" to "authenticated";

grant truncate on table "public"."meals_list" to "authenticated";

grant update on table "public"."meals_list" to "authenticated";

grant delete on table "public"."meals_list" to "service_role";

grant insert on table "public"."meals_list" to "service_role";

grant references on table "public"."meals_list" to "service_role";

grant select on table "public"."meals_list" to "service_role";

grant trigger on table "public"."meals_list" to "service_role";

grant truncate on table "public"."meals_list" to "service_role";

grant update on table "public"."meals_list" to "service_role";

grant delete on table "public"."restriction_reference" to "anon";

grant insert on table "public"."restriction_reference" to "anon";

grant references on table "public"."restriction_reference" to "anon";

grant select on table "public"."restriction_reference" to "anon";

grant trigger on table "public"."restriction_reference" to "anon";

grant truncate on table "public"."restriction_reference" to "anon";

grant update on table "public"."restriction_reference" to "anon";

grant delete on table "public"."restriction_reference" to "authenticated";

grant insert on table "public"."restriction_reference" to "authenticated";

grant references on table "public"."restriction_reference" to "authenticated";

grant select on table "public"."restriction_reference" to "authenticated";

grant trigger on table "public"."restriction_reference" to "authenticated";

grant truncate on table "public"."restriction_reference" to "authenticated";

grant update on table "public"."restriction_reference" to "authenticated";

grant delete on table "public"."restriction_reference" to "service_role";

grant insert on table "public"."restriction_reference" to "service_role";

grant references on table "public"."restriction_reference" to "service_role";

grant select on table "public"."restriction_reference" to "service_role";

grant trigger on table "public"."restriction_reference" to "service_role";

grant truncate on table "public"."restriction_reference" to "service_role";

grant update on table "public"."restriction_reference" to "service_role";

grant delete on table "public"."user_ingredient_preferences" to "anon";

grant insert on table "public"."user_ingredient_preferences" to "anon";

grant references on table "public"."user_ingredient_preferences" to "anon";

grant select on table "public"."user_ingredient_preferences" to "anon";

grant trigger on table "public"."user_ingredient_preferences" to "anon";

grant truncate on table "public"."user_ingredient_preferences" to "anon";

grant update on table "public"."user_ingredient_preferences" to "anon";

grant delete on table "public"."user_ingredient_preferences" to "authenticated";

grant insert on table "public"."user_ingredient_preferences" to "authenticated";

grant references on table "public"."user_ingredient_preferences" to "authenticated";

grant select on table "public"."user_ingredient_preferences" to "authenticated";

grant trigger on table "public"."user_ingredient_preferences" to "authenticated";

grant truncate on table "public"."user_ingredient_preferences" to "authenticated";

grant update on table "public"."user_ingredient_preferences" to "authenticated";

grant delete on table "public"."user_ingredient_preferences" to "service_role";

grant insert on table "public"."user_ingredient_preferences" to "service_role";

grant references on table "public"."user_ingredient_preferences" to "service_role";

grant select on table "public"."user_ingredient_preferences" to "service_role";

grant trigger on table "public"."user_ingredient_preferences" to "service_role";

grant truncate on table "public"."user_ingredient_preferences" to "service_role";

grant update on table "public"."user_ingredient_preferences" to "service_role";

grant delete on table "public"."user_profile" to "anon";

grant insert on table "public"."user_profile" to "anon";

grant references on table "public"."user_profile" to "anon";

grant select on table "public"."user_profile" to "anon";

grant trigger on table "public"."user_profile" to "anon";

grant truncate on table "public"."user_profile" to "anon";

grant update on table "public"."user_profile" to "anon";

grant delete on table "public"."user_profile" to "authenticated";

grant insert on table "public"."user_profile" to "authenticated";

grant references on table "public"."user_profile" to "authenticated";

grant select on table "public"."user_profile" to "authenticated";

grant trigger on table "public"."user_profile" to "authenticated";

grant truncate on table "public"."user_profile" to "authenticated";

grant update on table "public"."user_profile" to "authenticated";

grant delete on table "public"."user_profile" to "service_role";

grant insert on table "public"."user_profile" to "service_role";

grant references on table "public"."user_profile" to "service_role";

grant select on table "public"."user_profile" to "service_role";

grant trigger on table "public"."user_profile" to "service_role";

grant truncate on table "public"."user_profile" to "service_role";

grant update on table "public"."user_profile" to "service_role";

grant delete on table "public"."user_restriction_preferences" to "anon";

grant insert on table "public"."user_restriction_preferences" to "anon";

grant references on table "public"."user_restriction_preferences" to "anon";

grant select on table "public"."user_restriction_preferences" to "anon";

grant trigger on table "public"."user_restriction_preferences" to "anon";

grant truncate on table "public"."user_restriction_preferences" to "anon";

grant update on table "public"."user_restriction_preferences" to "anon";

grant delete on table "public"."user_restriction_preferences" to "authenticated";

grant insert on table "public"."user_restriction_preferences" to "authenticated";

grant references on table "public"."user_restriction_preferences" to "authenticated";

grant select on table "public"."user_restriction_preferences" to "authenticated";

grant trigger on table "public"."user_restriction_preferences" to "authenticated";

grant truncate on table "public"."user_restriction_preferences" to "authenticated";

grant update on table "public"."user_restriction_preferences" to "authenticated";

grant delete on table "public"."user_restriction_preferences" to "service_role";

grant insert on table "public"."user_restriction_preferences" to "service_role";

grant references on table "public"."user_restriction_preferences" to "service_role";

grant select on table "public"."user_restriction_preferences" to "service_role";

grant trigger on table "public"."user_restriction_preferences" to "service_role";

grant truncate on table "public"."user_restriction_preferences" to "service_role";

grant update on table "public"."user_restriction_preferences" to "service_role";


  create policy "Enable insert for users based on user_id"
  on "public"."user_profile"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "User access to dietary_profiles"
  on "public"."user_profile"
  as permissive
  for all
  to public
using ((auth.uid() = user_id));



